### ISSUE TITLE
Cant "repo init"

### ISSUE THREAD

**Issue by Split7fire** [rohantaneja/android_device_mediatek_mt6582#6]
Just tried to init using "repo init -u git://github.com/rohantaneja/android.git -b cm-13.0" and that not working.

Instead "repo init -u git://github.com/rohantaneja/android.git -b cm-13.0-mt92" works. Note mt92 addition.

**Comment by rohantaneja** [comment]
I haven't added cm-13.0 branch yet in manifest repository. I will add it soon. :100:

**Comment by Split7fire** [comment]
So, it is "ok" to repo with mt92? Because when repo done, i have problem with brunch: "no such target cm_mt6582-userdebug". I thought it is related.
Thanks for your work by the way 👍

**Comment by rohantaneja** [comment]
Update the vendorsetup.sh for that 👍🏼 
It will work just fine. Update framework values as per your device requirements!
