### ISSUE TITLE
libwebviewchromium.so ERROR

### ISSUE THREAD

**Issue by GMCadiom** [rohantaneja/android_device_mediatek_mt6582#9]
i used that command 
repo init -u git://github.com/rohantaneja/android.git -b cm-12.1
and made repo sync 
and ported the vendor and device to my device and start build but i got error that error 
what should i do to fix it ??
![screenshot from 2016-06-03 19 57 30](https://cloud.githubusercontent.com/assets/17429706/15988165/9e83791c-304e-11e6-9be9-3f021d6805be.png)
*\* note **
when i port vendor there are files not exist in my stock ROM
thanks ROHAN for your help anyway broooo <3 <3

**Comment by rohantaneja** [comment]
Use my vendor directly and at the end you can simply do minimal replacement to boot up the ROM.
